server {
    listen 80;
    server_name localhost;
    root /var/www/app/public;
    index index.php;

    # Logs
    access_log /var/log/nginx/access.log;
    error_log /var/log/nginx/error.log;

    location / {
        try_files $uri $uri/ /index.php$is_args$args;    }

    location ~ \.php$ {
        fastcgi_pass php:9000; # Pass PHP requests to the PHP-FPM container
        fastcgi_split_path_info ^(.+\.php)(/.*)$; # Split the URI into the script name and path info
        include fastcgi_params; # Include the default FastCGI parameters
        fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name; # Set the SCRIPT_FILENAME parameter to the real path of the script
        fastcgi_param DOCUMENT_ROOT $realpath_root; # Set the DOCUMENT_ROOT parameter to the real path of the root directory
        internal; # Prevent direct access to PHP files
    }

    location ~ \.(?:css|js|jpg|jpeg|png|gif|ico|svg|woff|woff2)$ {
        expires 30d; # Cache static assets for 30 days
        access_log off; # Disable access logs for static assets
    }

    location ~ /\.(?!well-known).* {
        deny all; # Deny access to hidden files, except for .well-known
    }

}
